root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - import
  - prettier
extends:
  - eslint:recommended
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  prettier/prettier: error
  no-unused-vars: warn
  '@typescript-eslint/no-unused-vars': warn
  no-console: off
  quotes: ['error', 'single']
