root: true
parser: "@typescript-eslint/parser"
plugins: 
  - "@typescript-eslint"
  - "prettier"
extends: 
  - eslint:recommended
  - airbnb
  - airbnb-typescript
  - prettier
parserOptions: 
  project: './tsconfig.json'